/****** Object:  StoredProcedure [dbo].[USP_CUESTIONARIO_PREGUNTA_ALL] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_CUESTIONARIO_PREGUNTA_ALL]
	@ID_CUESTIONARIO INT
AS
BEGIN
	DECLARE @ALL_ROWS bigint = 0;

	SELECT @ALL_ROWS = COUNT(1)
	FROM dbo.CUESTIONARIO_PREGUNTA
	WHERE ID_CUESTIONARIO = @ID_CUESTIONARIO;

	SELECT
	ROW_NUMBER() OVER(ORDER BY ID_CUESTIONARIO_PREGUNTA) AS FILA
	, @ALL_ROWS AS REGISTROS
	, ID_CUESTIONARIO_PREGUNTA
	, NOMBRE
	, PESO
	, ID_CUESTIONARIO
	FROM dbo.CUESTIONARIO_PREGUNTA
	WHERE ID_CUESTIONARIO = @ID_CUESTIONARIO;
END
GO

/****** Object:  StoredProcedure [dbo].[USP_CUESTIONARIO_PREGUNTA_INS] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_CUESTIONARIO_PREGUNTA_INS]
	    @NOMBRE VARCHAR(250)
	,   @PESO INT
	,   @ID_CUESTIONARIO INT
	,   @ID_CUESTIONARIO_PREGUNTA INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.CUESTIONARIO_PREGUNTA
	(NOMBRE, PESO, ID_CUESTIONARIO)
	VALUES (@NOMBRE, @PESO, @ID_CUESTIONARIO);

	SET @ID_CUESTIONARIO_PREGUNTA = @@IDENTITY
END
GO

/****** Object:  StoredProcedure [dbo].[USP_CUESTIONARIO_PREGUNTA_DEL_ALL] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_CUESTIONARIO_PREGUNTA_DEL_ALL]
	@ID_CUESTIONARIO INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE R
	FROM dbo.CUESTIONARIO_PREGUNTA_RESPUESTA R
	INNER JOIN dbo.CUESTIONARIO_PREGUNTA P ON P.ID_CUESTIONARIO_PREGUNTA = R.ID_CUESTIONARIO_PREGUNTA
	WHERE P.ID_CUESTIONARIO = @ID_CUESTIONARIO;

	DELETE FROM dbo.CUESTIONARIO_PREGUNTA
	WHERE ID_CUESTIONARIO = @ID_CUESTIONARIO;
END
GO

/****** Object:  StoredProcedure [dbo].[USP_CUESTIONARIO_PREGUNTA_RESPUESTA_ALL] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_CUESTIONARIO_PREGUNTA_RESPUESTA_ALL]
	@ID_CUESTIONARIO_PREGUNTA INT
AS
BEGIN
	DECLARE @ALL_ROWS bigint = 0;

	SELECT @ALL_ROWS = COUNT(1)
	FROM dbo.CUESTIONARIO_PREGUNTA_RESPUESTA
	WHERE ID_CUESTIONARIO_PREGUNTA = @ID_CUESTIONARIO_PREGUNTA;

	SELECT
	ROW_NUMBER() OVER(ORDER BY ID_PREGUNTA_RESPUESTA) AS FILA
	, @ALL_ROWS AS REGISTROS
	, ID_PREGUNTA_RESPUESTA
	, NOMBRE
	, ID_CUESTIONARIO_PREGUNTA
	FROM dbo.CUESTIONARIO_PREGUNTA_RESPUESTA
	WHERE ID_CUESTIONARIO_PREGUNTA = @ID_CUESTIONARIO_PREGUNTA;
END
GO

/****** Object:  StoredProcedure [dbo].[USP_CUESTIONARIO_PREGUNTA_RESPUESTA_INS] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[USP_CUESTIONARIO_PREGUNTA_RESPUESTA_INS]
	    @NOMBRE VARCHAR(250)
	,   @ID_CUESTIONARIO_PREGUNTA INT
	,   @ID_PREGUNTA_RESPUESTA INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.CUESTIONARIO_PREGUNTA_RESPUESTA
	(NOMBRE, ID_CUESTIONARIO_PREGUNTA)
	VALUES (@NOMBRE, @ID_CUESTIONARIO_PREGUNTA);

	SET @ID_PREGUNTA_RESPUESTA = @@IDENTITY
END
GO
