INSERT INTO BD_ugerdes_capacitagrd.dbo.CONFIGURACION (TEXTO_NOTIFICACION,TEXTO_NOTIFICACION_ADJUNTO,TEXTO_CERTIFICADO,TEXTO_DOCUMENTO,TEXTO_CONSTANCIA) VALUES
	 (N'<p>PRUEBA DE NOTIFICACION DE CORREO</p>

<p>&nbsp;</p>

<p>SALUDOS CORDIALES</p>

<p>EQUIPO UGERDES</p>
',N'<p>PRUEBA DE NOTIFICACION DE CORREO ADJUNTANDO TICKET DE INSCRIPCIO</p>

<p>&nbsp;</p>

<p>SALUDOS CORDIALES</p>

<p>EQUIPO UGERDES</p>
',N'<p>ESTIMADO JORGE LUIS NOS COMPLACE EN DECIRLE QUE USTEDE A APROBADO</p>
',N'<p>ESTIMADO USUARIO USTE TIENE PENDIENTES DOCUMENTOS POR ENVIAR</p>

<p>&nbsp;</p>
',N'<p>Prueba de constancia</p>
');
