CREATE VIEW UV_DATOS_EVENTOS
AS

SELECT 
  E.ID_EVENTO
, COD_EVENTO
, e.NOMBRE
, FECHA_INICIO
, FECHA_FIN
, NOMBRE_LUGAR
, e.ID_ESTADO
, me.NOMBRE as estado
, ID_UBIGEO
, md.CODIGO_DISTRITO 
, md.DEPARTAMENTO 
, md.PROVINCIA 
, md.DISTRITO 
, BANNER
, NUM_PARTICIPANTES
, DESCRIPCION
, ENLACE_WHATSAPP
, HORA_INICIO
, HORA_FIN
, RED_SOCIAL
, E.ID_TIPO_EVENTO
, MTE.NOMBRE TIPO_EVENTO
, E.ID_MODALIDAD
, MM.NOMBRE MODALIDAD
, GENERA_TICKET
, ENVIA_CORREO
, E.ID_ENCUESTA
, E2.NOMBRE ENCUESTA
, E.ID_CUESTIONARIO
, C.NOMBRE CUESTIONARIO
, FORMATO
, P.ID_PERSONA 
, P.NOMBRES 
, P.APELLIDO_PATERNO 
, P.APELLIDO_MATERNO 
, P.VALIDADO_PIDE 
, P.ID_TIPO_DOCUMENTO 
, DATEDIFF(year, P.FECHA_NACIMIENTO, GETDATE()) EDAD
, P.SEXO 
, P.EMAIL 
, P.CELULAR 

, P.ID_PROFESION 
, MP.NOMBRE PROFESION

, MTD.NOMBRE TIPO_DOCUMENTO
, P.NUM_DOCUMENTO 
, mmpp.nombre AS MODALIDA_PARTICIPANTE
, EP.ID_MODALIDAD AS ID_MODALIDA_PARTICIPANTE

, EP.LATITUD 
, EP.LONGITUD 
, P.ID_PAIS_NACIMIENTO 
, MP2.NOMBRE PAIS_NACIMIENTO
, PD.ID_PAIS_LABORA
, mp3.NOMBRE PAIS_LABORA
, PD.NOMBRE_ENTIDAD_OTRA 
, PD.NOMBRE_CARGO_OTRA 
, PD.ID_CARGO
, mc.NOMBRE CARGO

, PD.ID_ENTIDAD 
, me2.NOMBRE ENTIDAD
, PD.ID_DISTRITO ID_DISTRITO_ENTIDAD_LABORA
, md2.DEPARTAMENTO DEPARTAMENTO_ENTIDAD_LABORA
, md2.PROVINCIA PROVINCIA_ENTIDAD_LABORA
, md2.DISTRITO DISTRITO_ENTIDAD_LABORA


FROM dbo.EVENTO e
LEFT JOIN DBO.MAE_ESTADO me 
ON E.ID_ESTADO = ME.ID_ESTADO 
LEFT JOIN DBO.MAE_DISTRITO md 
on e.ID_UBIGEO = md.ID_DISTRITO 
LEFT JOIN DBO.MAE_TIPO_EVENTO mte 
ON E.ID_TIPO_EVENTO = MTE.ID_TIPO_EVENTO 
LEFT JOIN DBO.MAE_MODALIDAD mm 
ON E.ID_MODALIDAD = MM.ID_MODALIDAD 
LEFT JOIN DBO.CUESTIONARIO c 
ON E.ID_CUESTIONARIO = C.ID_CUESTIONARIO 
LEFT JOIN DBO.ENCUESTA e2 
ON E.ID_ENCUESTA = E2.ID_ENCUESTA 
LEFT JOIN DBO.EVENTO_PARTICIPANTE ep 

LEFT JOIN DBO.MAE_MODALIDAD mmpp
ON ep.ID_MODALIDAD = mmpp.ID_MODALIDAD

ON EP.ID_EVENTO = EP.ID_EVENTO 
LEFT JOIN DBO.PERSONA p 
ON EP.ID_PERSONA = P.ID_PERSONA 
LEFT JOIN DBO.PERSONA_DATA pd 
ON EP.ID_PERSONA_DATA = PD.ID_PERSONA_DATA AND EP.ID_PERSONA = P.ID_PERSONA 
LEFT JOIN DBO.MAE_TIPO_DOCUMENTO mtd 
ON P.ID_TIPO_DOCUMENTO = MTD.ID_TIPO_DOCUMENTO 
LEFT JOIN DBO.MAE_PROFESION mp 
ON P.ID_PERSONA = MP.ID_PROFESION 
LEFT JOIN DBO.MAE_PAIS mp2 
ON P.ID_PAIS_NACIMIENTO = MP2.ID_PAIS 
LEFT JOIN DBO.MAE_PAIS mp3 
ON PD.ID_PAIS_LABORA = MP3.ID_PAIS 
LEFT JOIN DBO.MAE_ENTIDAD me2 
ON PD.ID_ENTIDAD = ME2.ID_ENTIDAD 
LEFT JOIN DBO.MAE_CARGO mc 
ON PD.ID_CARGO = MC.ID_CARGO 
LEFT JOIN DBO.MAE_DISTRITO md2 
ON PD.ID_DISTRITO = MD2.ID_DISTRITO;