/****** Corrige la referencia circular obligatoria entre CUESTIONARIO_PREGUNTA y
        CUESTIONARIO_PREGUNTA_RESPUESTA.

        CUESTIONARIO_PREGUNTA.ID_CUESTIONARIO_RESPUESTA -> CUESTIONARIO_PREGUNTA_RESPUESTA.ID_PREGUNTA_RESPUESTA
        CUESTIONARIO_PREGUNTA_RESPUESTA.ID_CUESTIONARIO_PREGUNTA -> CUESTIONARIO_PREGUNTA.ID_CUESTIONARIO_PREGUNTA

        Ambas columnas son NOT NULL, lo que impide insertar cualquiera de las dos filas primero.
        La relacion 1 a N entre pregunta y sus opciones de respuesta ya queda representada por
        CUESTIONARIO_PREGUNTA_RESPUESTA.ID_CUESTIONARIO_PREGUNTA, por lo que se elimina la columna
        redundante y su FK. ******/

ALTER TABLE [dbo].[CUESTIONARIO_PREGUNTA] DROP CONSTRAINT [FK_CUESTIONARIO_PREGUNTA_CUESTIONARIO_PREGUNTA_RESPUESTA]
GO

ALTER TABLE [dbo].[CUESTIONARIO_PREGUNTA] DROP COLUMN [ID_CUESTIONARIO_RESPUESTA]
GO
